<?php

require_once(dirname(__FILE__) . '/config.inc.php');
require_once(dirname(__FILE__) . '/adodb5/adodb.inc.php');

//----------------------------------------------------------------------------------------

$parents = array();

function makeset($x) {
	global $parents;
	
	$parents[$x] = $x;
}

function find($x) {
	global $parents;
	
	if ($x == $parents[$x]) {
		return $x;
	} else {
		return find($parents[$x]);
	}
}

function union($x, $y) {
	global $parents;
	
	$x_root = find($x);
	$y_root = find($y);
	$parents[$x_root] = $y_root;
	
}



//--------------------------------------------------------------------------------------------------
$db = NewADOConnection('mysql');
$db->Connect("localhost", 
	$config['db_user'] , $config['db_passwd'] , $config['db_name']);

// Ensure fields are (only) indexed by column name
$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;

$db->EXECUTE("set names 'utf8'"); 


$genera = array('Acanthopsis',
'Andrographis',
'Asystasia',
'Beloperone',
'Chaetothylax',
'Dianthera',
'Acer',
'Adiantopsis',
'Adiantum',
'Aleuritopteris',
'Allosurus',
'Cryptogramma',
'Jamesonia',
'Onychium',
'Pellaea',
'Pentagramma',
'Polianthes',
'Daggodora',
'Dinteranthus',
'Drosanthemopsis',
'Komsbergella',
'Sanianthos',
'Alangium',
'Allium',
'Dipterostemon',
'Aloe',
'Gastonialoe',
'Tulista',
'Alstroemeria',
'Achyropsis',
'Aerva',
'Alternanthera',
'Amaranthus',
'Arthrocaulon',
'Arthroceras',
'Belowia',
'Philoxerus',
'Wadithamnus',
'Apodolirion',
'Myostemma',
'Narcissus',
'Phaedranassa',
'Zephyranthes',
'Mauria',
'Afroguatteria',
'Alphonsea',
'Goniothalamus',
'Miliusa',
'Monanthotaxis',
'Oxandra',
'Sphaerocoryne',
'Wangia',
'Xylopia',
'Chlorophytum',
'Thysanotus',
'Angelica',
'Annesorhiza',
'Conium',
'Cymbocarpum',
'Hydrocotyle',
'Lomatium',
'Normantha',
'Pastinaca',
'Pimpinella',
'Seseli',
'Sillaphyton',
'Sium',
'Smyrnium',
'Anemotrochus',
'Apocynum',
'Poacynum',
'Ilex',
'Alocasia',
'Biarum',
'Dieffenbachia',
'Ooia',
'Schismatoglottis',
'Aralia',
'Botryodendrum',
'Brassaiopsis',
'Dendropanax',
'Hedera',
'Heptapleurum',
'Kalopanax',
'Macropanax',
'Panax',
'Schefflera',
'Aiphanes',
'Areca',
'Attalea',
'Guihaia',
'Pholidostachys',
'Syagrus',
'Synechanthus',
'Aristolochia',
'Asarum',
'Aspidoglossum',
'Brachystelma',
'Ceropegia',
'Cynanchum',
'Heterostemma',
'Hoya',
'Matelea',
'Periglossum',
'Piaranthus',
'Tylodontia',
'Vincetoxicum',
'Asparagus',
'Eremurus',
'Asplenium',
'Achillea',
'Ageratum',
'Anacyclus',
'Aplotaxis',
'Baccharis',
'Centaurea',
'Chrysocephalum',
'Cirsium',
'Cremanthodium',
'Distephanus',
'Erigeron',
'Espeletia',
'Eupatorium',
'Gnaphalium',
'Gundelia',
'Gutierrezia',
'Helianthus',
'Helichrysum',
'Hieracium',
'Humbertacalia',
'Hymenothrix',
'Isocarpha',
'Lagenophora',
'Lanugothamnus',
'Lapidia',
'Launaea',
'Liabum',
'Ligularia',
'Lomanthus',
'Macroclinidium',
'Madacarpus',
'Maschalostachys',
'Mikania',
'Munnozia',
'Nothoschkuhria',
'Parasenecio',
'Pertya',
'Perymenium',
'Petasites',
'Picradeniopsis',
'Pilosella',
'Podachaenium',
'Santolina',
'Saussurea',
'Senecio',
'Solidago',
'Symphyotrichum',
'Synotis',
'Taraxacum',
'Tridax',
'Turanecio',
'Verbesina',
'Vernonanthura',
'Vernonia',
'Balanophora',
'Impatiens',
'Begonia',
'Berberis',
'Epimedium',
'Alnus',
'Adenocalymma',
'Jacaranda',
'Neojobertia',
'Phyllarthron',
'Tanaecium',
'Blechnum',
'Parablechnum',
'Andersonglossum',
'Cryptantha',
'Eritrichium',
'Euploca',
'Iberodes',
'Mapuchea',
'Mimophytum',
'Omphalodes',
'Onosma',
'Tournefortia',
'Trigonotis',
'Alyssum',
'Anzhengxia',
'Asta',
'Biscutella',
'Boechera',
'Brassica',
'Brassica-napus',
'Descurainia',
'Draba',
'Erysimum',
'Eutrema',
'Hormathophylla',
'Lepidium',
'Matthiola',
'Metashangrilaia',
'Noccaea',
'Pterolobium',
'Raphanus',
'Rudolf-kamelinia',
'Barfussia',
'Bromelia',
'Goudaea',
'Gregbrownia',
'Guzmania',
'Jagrantia',
'Josemania',
'Lemeltonia',
'Lutheria',
'Pitcairnia',
'Pseudalcantarea',
'Puya',
'Racinaea',
'Sincoraea',
'Steyerbromelia',
'Stigmatodon',
'Tillandsia',
'Vriesea',
'Wallisia',
'Zizkaea',
'Barrera',
'Thismia',
'Bursera',
'Commiphora',
'Dacryodes',
'Protium',
'Bolivicereus',
'Bolivihanburya',
'Borzicereus',
'Corynopuntia',
'Echinocactus',
'Echinocereus',
'Escobaria',
'Mammillaria',
'Mariottia',
'Morawetzia',
'Opuntia',
'Polascontria',
'Stenocereus',
'Wittiocactus',
'Tachigali',
'Campanulastrum',
'Lobelia',
'Lysipomia',
'Wahlenbergia',
'Abelia',
'Viburnum',
'Acanthophyllum',
'Arenaria',
'Cerastium',
'Coromelandrum',
'Gypsophila',
'Odontostemma',
'Polycarpaea',
'Sabulina',
'Sagina',
'Silene',
'Solitaria',
'Stellaria',
'Allocasuarina',
'Crossopetalum',
'Reissantia',
'Cercidiphyllum',
'Chenopodium',
'Dysphania',
'Lipandra',
'Petrosimonia',
'Salicornia',
'Caraipa',
'Clusia',
'Garcinia',
'Hypericum',
'Tovomita',
'Colchicum',
'Commelina',
'Murdannia',
'Tradescantia',
'Aspidistra',
'Tricyrtis',
'Argyreia',
'Convolvulus',
'Ipomoea',
'Rivea',
'Cornus',
'Carpinus',
'Costus',
'Dudleya',
'Echeveria',
'Hylostachys',
'Petrosedum',
'Reidmorania',
'Sedum',
'Telephium',
'Lagenaria',
'Luffa',
'Momordica',
'Trichosanthes',
'Callitris',
'Cyathea',
'Cycas',
'Carex',
'Cyperus',
'Ficinia',
'Mapania',
'Rhynchospora',
'Schoenus',
'Davallia',
'Katoella',
'Dennstaedtia',
'Lindsaea',
'Microlepia',
'Odontosoria',
'Pteridium',
'Shortia',
'Tapura',
'Dioscorea',
'Cephalaria',
'Dracaena',
'Sansevieria',
'Dryopteris',
'Pleocnemia',
'Polystichum',
'Tectaria',
'Diospyros',
'Elatine',
'Leucopogon',
'Stenanthera',
'Equisetum',
'Agapetes',
'Diplycosia',
'Erica',
'Rhododendron',
'Vaccinium',
'Eriocaulon',
'Actephila',
'Aemaralmeida',
'Breynia',
'Croton',
'Dalechampia',
'Euphorbia',
'Gymnanthes',
'Jatropha',
'Maesobotrya',
'Manihot',
'Petalodiscus',
'Sauropus',
'Savia',
'Synostemon',
'Alysicarpus',
'Amicia',
'Astragalus',
'Erythrina',
'Hedysarum',
'Indigofera',
'Lupinus',
'Mucuna',
'Onobrychis',
'Oxytropis',
'Rhynchosia',
'Robinia',
'Sesbania',
'Abarema',
'Acacia',
'Adenodolichos',
'Bituminaria',
'Callerya',
'Chamaecytisus',
'Coulteria',
'Dalbergia',
'Dialium',
'Eriosema',
'Erythrostemon',
'Laburnum',
'Leptoderris',
'Lespedeza',
'Lessertia',
'Lonchocarpus',
'Medicago',
'Melilotoides',
'Millettia',
'Ormocarpopsis',
'Sanjappa',
'Spartium',
'Trifolium',
'Vicia',
'Vigna',
'Quercus',
'Exacum',
'Gentiana',
'Swertia',
'Geranium',
'Billolivia',
'Codonanthanthus',
'Didymocarpus',
'Oreocharis',
'Petrocodon',
'Primulina',
'Sphaerorrhiza',
'Ceradenia',
'Prosaptia',
'Radiogrammitis',
'Myriophyllum',
'Hanguana',
'Heliconia',
'Charybdis',
'Drimia',
'Ornithogalum',
'Scilla',
'Vera-duthiea',
'Calyptranthe',
'Cornidia',
'Heteromalla',
'Hortensia',
'Hydrangea',
'Philadelphus',
'Platycrater',
'Cosmanthus',
'Phacelia',
'Paronychia',
'Eriophyton',
'Aegiphila',
'Betonica',
'Calamintha',
'Clerodendrum',
'Clinopodium',
'Coleus',
'Eriope',
'Gmelina',
'Hemigenia',
'Kudrjaschevia',
'Lagochilus',
'Lagopsis',
'Lasemia',
'Lavandula',
'Leonurus',
'Mentha',
'Phlomoides',
'Plectranthus',
'Salvia',
'Scutellaria',
'Stachys',
'Teucrium',
'Thymus',
'Ziziphora',
'Aniba',
'Cryptocarya',
'Cubeba',
'Damburneya',
'Eschweilera',
'Aquilicia',
'Pinguicula',
'Fritillaria',
'Gagea',
'Linum',
'Bolbitis',
'Psittacanthus',
'Dendrolycopodium',
'Diphasiastrum',
'Huperzia',
'Lycopodium',
'Phlegmariurus',
'Selago',
'Lagerstroemia',
'Magnolia',
'Amorimia',
'Byrsonima',
'Stigmaphyllon',
'Tetrapterys',
'Abutilon',
'Sida',
'Alloneuron',
'Bertolonia',
'Blakea',
'Chaetogastra',
'Fordiophyton',
'Melastoma',
'Memecylon',
'Meriania',
'Miconia',
'Microlicia',
'Phyllagathis',
'Pleroma',
'Cissampelos',
'Nymphoides',
'Macrosamanea',
'Senegalia',
'Limeum',
'Eremophila',
'Morella',
'Myrica',
'Myristica',
'Ardisia',
'Beaufortia',
'Calyptranthes',
'Eugenia',
'Jambosa',
'Malleostemon',
'Metrosideros',
'Myrcia',
'Myrcianthes',
'Psidium',
'Syzygium',
'Nepenthes',
'Chionanthus',
'Fraxinus',
'Jasminum',
'Noronhia',
'Phillyrea',
'Oleandra',
'Hartmannia',
'Ocimastrum',
'Oenothera',
'Pseudo-oenothera',
'Acianthera',
'Acropera',
'Anathallis',
'Andinia',
'Angraecum',
'Aspidogyne',
'Bidoupia',
'Brachionidium',
'Bulbophyllum',
'Bunochilus',
'Campylocentrum',
'Catasetum',
'Chloraea',
'Cleisostoma',
'Coelogyne',
'Corunastylis',
'Coryanthes',
'Corybas',
'Crepidium',
'Cryptocentrum',
'Cymbidium',
'Dactylodenia',
'Dactylorhiza',
'Dasyglossum',
'Dendrobium',
'Dendrochilum',
'Eltrolexia',
'Encabarcenia',
'Encalaelia',
'Epidendrum',
'Epipactis',
'Flickingeria',
'Gastrochilus',
'Georgefara',
'Glomera',
'Gomesa',
'Gongora',
'Greenwoodiella',
'Guarischomtonia',
'Guarlaeburgkia',
'Gymnadenia',
'Habenaria',
'Hetaeria',
'Himantoglossum',
'Kodamaara',
'Laelia',
'Lepanthes',
'Liparis',
'Longhueiara',
'Masdevallia',
'Maxillaria',
'Microchilus',
'Neodryas',
'Neooreophilus',
'Neottia',
'Nervilia',
'Oligochaetochilus',
'Oliveriana',
'Ophrys',
'Orchis',
'Ottoara',
'Paphiopedilum',
'Pectinariella',
'Phalaenopsis',
'Phreatia',
'Platanthera',
'Pleione',
'Pleurothallis',
'Podochilus',
'Ponthieva',
'Pradhanara',
'Prasophyllum',
'Prosthechea',
'Pseudadenia',
'Pseudorchis',
'Pseudorhiza',
'Psyburgkia',
'Schombolaelia',
'Schomburgkia',
'Schomcatanthe',
'Schomcaulaelia',
'Schomcaulattleya',
'Schomkeria',
'Schomrhyncattleya',
'Serapias',
'Siederella',
'Sigmatostalix',
'Silvorchis',
'Speculantha',
'Stanhopea',
'Stelis',
'Stellilabium',
'Telipogon',
'Thrixspermum',
'Trichononcos',
'Trigonochilum',
'Vanda',
'Vanilla',
'Yuwengangara',
'Oxalis',
'Paeonia',
'Benstonea',
'Capnogonium',
'Corydalis',
'Glaucium',
'Papaver',
'Stylophorum',
'Ceratopteris',
'Parnassia',
'Passiflora',
'Tetrapathea',
'Pentaphragma',
'Picea',
'Pinus',
'Piper',
'Agropyron',
'Arundinella',
'Avena',
'Bouteloua',
'Bromus',
'Chloothamnus',
'Coleataenia',
'Cortaderia',
'Dendrocalamus',
'Deschampsia',
'Dichanthelium',
'Digitaria',
'Distichlis',
'Elymus',
'Eremitis',
'Eriachne',
'Fargesia',
'Festuca',
'Hymenachne',
'Iseilema',
'Koeleria',
'Merostachys',
'Orthacanthus',
'Panicum',
'Paspalum',
'Poa',
'Pseudarrhenatherum',
'Ruhooglandia',
'Saccharum',
'Schizostachyum',
'Simplicia',
'Stipa',
'Torreya',
'Tridentopsis',
'Triplasiella',
'Tripogonella',
'Trisetopsis',
'Trisetopsotrichon',
'Tritipyrum',
'Tzveleviochloa',
'Urochloa',
'Widjajachloa',
'Zaqiqah',
'Zizaniopsis',
'Jenmaniella',
'Oserya',
'Rhyncholacis',
'Acanthocladus',
'Polygala',
'Avicularia',
'Bistorta',
'Fagopyrum',
'Persicaria',
'Polygonum',
'Androsace',
'Lysimachia',
'Primula',
'Soldanella',
'Pteris',
'Frangula',
'Rhamnus',
'Smythea',
'Agrimonia',
'Alchemilla',
'Amelancus',
'Argentina',
'Aria',
'Ariamelyrus',
'Ariosorbus',
'Arisorbanchier',
'Aronia',
'Aroniaria',
'Bakeria',
'Bernullia',
'Cerasus',
'Ceropadus',
'Chabertia',
'Chamaearia',
'Chamariosorbus',
'Chavinia',
'Cotacantha',
'Cottetia',
'Crataegus',
'Crataronibus',
'Crepinia',
'Cydocydonia',
'Cydosorbus',
'Drymogaria',
'Fallania',
'Fragiphora',
'Gervasia',
'Idaeobatus',
'Malus',
'Mesaronibus',
'Photacantha',
'Potenaria',
'Potentilla',
'Prunus',
'Pyrosorbaronia',
'Pyrosorbus',
'Pyrus',
'Rosa',
'Rubus',
'Sibbaldianthe',
'Sorbacantha',
'Sorbomespilus',
'Sorbotoraria',
'Sorbus',
'Spiraea',
'Tetraglochin',
'Tormaria',
'Tormariosorbus',
'Asperula',
'Cinchona',
'Erithalis',
'Etericius',
'Foonchewia',
'Galium',
'Ixora',
'Knoxia',
'Kochummenia',
'Lasianthus',
'Leptopetalum',
'Margaritopsis',
'Mycetia',
'Oxyanthus',
'Palicourea',
'Pentagonia',
'Peponidium',
'Pseudosabicea',
'Psychotria',
'Puffia',
'Pyrostria',
'Randia',
'Ridsdalea',
'Rubia',
'Sabicea',
'Simira',
'Singaporandia',
'Spermacoce',
'Spiradiclis',
'Tetramerium',
'Amyris',
'Bellucia',
'Casimiroa',
'Glycosmis',
'Haplophyllum',
'Murraya',
'Spathelia',
'Blakwellia',
'Populus',
'Salix',
'Serjania',
'Englerophytum',
'Pouteria',
'Sideroxylon',
'Pentachlaena',
'Micranthes',
'Saxifraga',
'Anemia',
'Aphyllon',
'Castilleja',
'Erythranthe',
'Linaria',
'Lindernia',
'Neobartsia',
'Orobanche',
'Pedicularis',
'Phelipanche',
'Phelypaea',
'Scrophularia',
'Synthyris',
'Verbascum',
'Selaginella',
'Pitavia',
'Cestrum',
'Deprea',
'Jaltomata',
'Solanum',
'Symplocos',
'Camellia',
'Erotium',
'Pyrenaria',
'Amauropelta',
'Cyclosorus',
'Goniopteris',
'Lastrea',
'Parathelypteris',
'Stegnogramma',
'Thelypteris',
'Lasiosiphon',
'Pimelea',
'Brownlowia',
'Trapa',
'Tetratheca',
'Trillium',
'Typha',
'Celtis',
'Ulmus',
'Elatostema',
'Valeriana',
'Glandularia',
'Verbena',
'Anchietea',
'Rinorea',
'Viola',
'Cyphostemma',
'Vitis',
'Antrophyum',
'Erisma',
'Athyrium',
'Cystopteris',
'Deparia',
'Hypodematium',
'Zamia',
'Althenia',
'Amomum',
'Etlingera',
'Hedychium',
'Hornstedtia',
'Monolophus',
'Tetraena');

$genera=array('Tetraena');

foreach ($genera as $genus)
{
	$names = array();
	
	$sql = 'SELECT * FROM names WHERE `Genus` = "' . $genus . '"';

	$result = $db->Execute($sql);
	if ($result == false) die("failed [" . __LINE__ . "]: " . $sql);
	while (!$result->EOF) 
	{
		$record = new stdclass;
		$record->id = $result->fields['Id'];
		$record->name = $result->fields['Full_name_without_family_and_authors'];
		$record->authors = $result->fields['Authors'];
		$record->year = $result->fields['Publication_year_full'];
		$record->rank = $result->fields['Rank'];
		
		if (preg_match('/^(?<year>[0-9]{4})/', $record->year, $m))
		{
			$record->year = $m['year'];
		}
		
		if (preg_match('/\d+-(?<source>\d+)$/', $record->id, $m))
		{
			$record->source = $m['source'];
		}
		
		$names[] = $record;
		$result->MoveNext();	
	}


	//print_r($names);
	
	$n = count($names);
	if ($n > 1)
	{
	
		for ($i = 0; $i < $n; $i++)
		{
			makeset($i);
		}

		for ($i = 1; $i < $n; $i++)
		{
			for ($j = 0; $j < $i; $j++)
			{
				$v1 = $names[$i]->name . ' ' . $names[$i]->authors . ' ' . $names[$j]->rank;
				$v2 = $names[$j]->name . ' ' . $names[$j]->authors . ' ' . $names[$j]->rank;

				if ($v1 == $v2) {
					union($i, $j);
				}
			}
		}
	
		$clusters = array();
	
		for ($i = 0; $i < $n; $i++)
		{
			$p = $parents[$i];
		
			if (!isset($clusters[$p]))
			{
				$clusters[$p] = array();
			}
			$clusters[$p][] = $i;
		}
		
		//print_r($clusters);
		
		foreach ($clusters as $k => $v)
		{
			$cluster_id = $names[$v[0]]->id;
			if (count($v) == 1)
			{
				echo "UPDATE `names` SET `ClusterId`='$cluster_id' WHERE Id='" . $names[$v[0]]->id . "';" . "\n";
			}
			else
			{
				//echo "-- cluster\n";
				foreach ($v as $i)
				{
					if ($names[$i]->source == 1)
					{
						$cluster_id = $names[$i]->id;
					}
				}
				echo "-- $cluster_id\n";
				
				foreach ($v as $i)
				{
					//echo $names[$i]->source . ' ' . $names[$i]->name . ' ' . $names[$i]->authors . ' ' . $names[$j]->rank . "\n";
					
					echo "UPDATE `names` SET `ClusterId`='$cluster_id' WHERE Id='" . $names[$i]->id . "';" .  " -- " . $names[$i]->name . "\n";
				}
				echo "-- \n";
			}
					
		}
	}
	



}

?>